FROM node:16-alpine3.14


LABEL version="1.0"
LABEL description="React Frontend for the Real Estate Api"


WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . .

CMD ["npm", "run", "start" ]
